### ISSUE TITLE
Claim prediction showing either 0 or 100

### ISSUE THREAD

**Issue by pivettamarcos** [titipata/detecting-scientific-claim#22]
For any sentence with claims detected, the probability score is either 0 or 100, never a value inbetween. On the image you show, there are decimal places.

**Comment by titipata** [comment]
Hi @pivettamarcos, yes, for the demo, I put the output from dense network to Conditional Random Field (CRF) layer which gives out 1,0 prediction. That's why you see score only 0 or 100. If we use the dense network without the CRF layer, it will give out probability output.
