### ISSUE TITLE
Edit annotation tool

### ISSUE THREAD

**Issue by titipata** [titipata/detecting-scientific-claim#6]
Now, we have a light version in [`annotation_tool`](https://github.com/titipata/detecting-scientific-claim/tree/master/annotation_tool) folder.

TODOS

- [ ] move start tagging button in the middle
- [ ] edit submit button in tagging page to the middle
- [ ] edit nav bar on laptop screen and mobile
- [ ] make progress bar checking how many tags already done by a user
- [ ] fix log-in page which has weird color right now
- [ ] display `CLAIM` tag to sentence after clicking or highlight the sentence

**Comment by bluenex** [comment]
## Progress

- [ ] move start tagging button in the middle
- [ ] edit submit button in tagging page to the middle
- [ ] edit nav bar on laptop screen and mobile
- [ ] make progress bar checking how many tags already done by a user
- [ ] fix log-in page which has weird color right now
- [ ] display `CLAIM` tag to sentence after clicking or highlight the sentence

**Comment by bluenex** [comment]
@titipata 
> make progress bar checking how many tags already done by a user

I'm not sure whether this can be done by pure CSS. 🙁

**Comment by titipata** [comment]
I will close this issue via 9715cfd
